[package]
name = "a5"
version = "0.1.0"
edition = "2024"
description = "Rust implementation of A5"
license = "Apache-2.0"
repository = "https://github.com/felixpalmer/a5-rs"

[lib]
path = "src/lib.rs"

[dev-dependencies]
approx = "0.5.1"
